# Amazon
- name: install nginx and modules in Linux
  become: yes
  yum: pkg={{item}} state=latest
  with_items:
    - nginx
    - nginx-mod-http-image-filter
    - nginx-all-modules
    - nginx-mod-http-xslt-filter
    - nginx-mod-http-geoip
    - nginx-mod-stream
    - nginx-mod-http-perl
    - nginx-mod-mail
  notify:
    - Start Nginx
  when:
    - ansible_facts['distribution'] == "Amazon"

# Ubuntu
- name: install nginx in Ubuntu
  become: yes
  apt: 
    pkg: nginx
    state: latest
    update_cache: true
  notify:
    - Start Nginx
  when:
    - ansible_facts['distribution'] == "Ubuntu"


# index.html 변경 (Linux & Ubuntu 동일)
- name: Create Page Change
  become: yes
  copy: 
    src: /var/lib/jenkins/workspace/WEB_image/teamb/playbook_web/roles/nginx/webpages/index.html 
    dest: /usr/share/nginx/html/index.html
  notify:
    - Reload Nginx